version: '3.7'
services:
  java:
    build:
      context: ./java
      args:
        - TELEMETRY_DESTINATION=applicationinsightssdk
    ports:
      - "8080:8080"
    networks:
      - demo      
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=java-demo
      - APPLICATIONINSIGHTS_PREVIEW_INSTRUMENTATION_AZURE_SDK_ENABLED=true
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - EVENTHUB_CONNECTION_STRING=${EVENTHUB_CONNECTION_STRING}
      - EVENTHUB_NAME=${EVENTHUB_NAME}
      - CHECKPOINT_STORAGE_ACCOUNT=${CHECKPOINT_STORAGE_ACCOUNT}
      - CHECKPOINT_STORAGE_ACCESS_KEY=${CHECKPOINT_STORAGE_ACCESS_KEY}
      - CHECKPOINT_CONTAINER_NAME=${CHECKPOINT_CONTAINER_NAME}   
  dotnet:
    build: ./dotnet
    ports:
      - "5000:80"
    networks:
      - demo      
    depends_on:
      - java
    environment:
      - TELEMETRY_DESTINATION=applicationinsightssdk      
      - ApplicationInsights:InstrumentationKey=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - EventHub:ConnectionString=${EVENTHUB_CONNECTION_STRING}
      - EventHub:EventHubName=${EVENTHUB_NAME}
      - Storage:ConnectionString=${CHECKPOINT_STORAGE_CONNECTION_STRING}
      - Storage:BlobContainerName=${CHECKPOINT_CONTAINER_NAME}
networks:
  demo:
