spring:
  application:
    name: java-tracing-demo
  cloud:
    azure:
      eventhub:
        connection-string: Endpoint=sb://tracingdemohub.servicebus.windows.net/;SharedAccessKeyName=default;SharedAccessKey=nsXIr17MHDaxtMUbptVOQOS9OQ0ZJ2qPPPxeATCCiIo=;
        checkpoint-storage-account: javachpnt
        checkpoint-access-key: vQe4XRU4ymlew0BI0B1a6YT1234v4QN67P1UjrtX8BHFaG6r5a4NfsZHjwd6MXYqFIr3Rl4UmPTdbF5O/Mv/iA==
        checkpoint-container: checkpoints
        eventhub-name: javahub
      storage:
        connection-string: DefaultEndpointsProtocol=https;AccountName=javachpnt;AccountKey=vQe4XRU4ymlew0BI0B1a6YT1234v4QN67P1UjrtX8BHFaG6r5a4NfsZHjwd6MXYqFIr3Rl4UmPTdbF5O/Mv/iA==;EndpointSuffix=core.windows.net
        queue-name: testme
      eventgrid:
        endpoint: https://limolkova-eventgrid.westus2-1.eventgrid.azure.net/api/events
        key: m1xT7ZfDEfhui/kj/N4/f+Q82ovt0uS66b98oltZ0A0=

    stream:
      bindings:
        consume-in-0:
          destination: javahub
          group: $Default

      eventhub:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
      function:
        definition: consume;
      poller:
        initial-delay: 0
        fixed-delay: 1000